## Question 3 

In this question you will use Pandas to read, clean, and append several data files from the National Health and Nutrition Examination Survey NHANES. We will use the data you prepare in this question as the starting point for analyses in one or more future problem sets. For this problem, you should use the four cohorts spanning the years 2011-2018. 

a. Use Python and Pandas to read and append the demographic datasets keeping only columns containing the unique ids (SEQN), age (RIDAGEYR), race and ethnicity (RIDRETH3), education (DMDEDUC2), and marital status (DMDMARTL), along with the following variables related to the survey weighting: (RIDSTATR, SDMVPSU, SDMVSTRA, WTMEC2YR, WTINT2YR). Add an additional column identifying to which cohort each case belongs. Rename the columns with literate variable names using all lower case and convert each column to an appropriate type. Finally, save the resulting data frame to a serialized “round-trip” format of your choosing (e.g. pickle, feather, or parquet).

In [ ]:
def get_gender(x):
    """
    Recode the gender column in a data frame

    Parameters
    ----------
    x : dataframe
        the gender column is to be change.

    Returns
    -------
    the changed column.

    """
    if x["gender"] == 1:
        return "Male"
    elif x["gender"] == 2:
        return "Female"
    else:
        return np.nan

In [ ]:
df1 = pd.read_sas('DEMO_G.XPT')
df1 = df1[['SEQN', 'RIDAGEYR', 'RIDRETH3', 'DMDEDUC2', 'DMDMARTL',
          'RIDSTATR', 'SDMVPSU', 'SDMVSTRA', 'WTMEC2YR', 'WTINT2YR']]
n_df1 = df1.shape[0]
df1['cohort of the case'] = ['2011-2012'] * n_df1

dic_df1 = {}
for name in df1.columns:
    dic_df1[name] = list(df1[name])
df1_frame = pd.DataFrame(
    dic_df1, index = list(range(1, n_df1+1))
)


df2 = pd.read_sas('DEMO_H.XPT')
df2 = df2[['SEQN', 'RIAGENDER', 'RIDAGEYR', 'RIDRETH3', 'DMDEDUC2', 'DMDMARTL',
          'RIDSTATR', 'SDMVPSU', 'SDMVSTRA', 'WTMEC2YR', 'WTINT2YR']]
n_df2 = df2.shape[0]
df2['cohort of the case'] = ['2013-2014'] * n_df2

dic_df2 = {}
for name in df2.columns:
    dic_df2[name] = list(df2[name])
df2_frame = pd.DataFrame(
    dic_df2, index = list(range(n_df1 + 1, n_df1 + n_df2 + 1))
)

df3 = pd.read_sas('DEMO_I.XPT')
df3 = df3[['SEQN', 'RIAGENDER', 'RIDAGEYR', 'RIDRETH3', 'DMDEDUC2', 'DMDMARTL',
          'RIDSTATR', 'SDMVPSU', 'SDMVSTRA', 'WTMEC2YR', 'WTINT2YR']]
n_df3 = df3.shape[0]
df3['cohort of the case'] = ['2015-2016'] * n_df3

dic_df3 = {}
for name in df3.columns:
    dic_df3[name] = list(df3[name])
df3_frame = pd.DataFrame(
    dic_df3, index = list(range(n_df1 + n_df2 + 1, n_df1 + n_df2 + 
                                n_df3 + 1))
)

df4 = pd.read_sas('DEMO_J.XPT')
df4 = df4[['SEQN', 'RIAGENDER', 'RIDAGEYR', 'RIDRETH3', 'DMDEDUC2', 'DMDMARTL',
          'RIDSTATR', 'SDMVPSU', 'SDMVSTRA', 'WTMEC2YR', 'WTINT2YR']]
n_df4 = df4.shape[0]
df4['cohort of the case'] = ['2017-2018'] * n_df4

dic_df4 = {}
for name in df4.columns:
    dic_df4[name] = list(df4[name])
df4_frame = pd.DataFrame(
    dic_df4, index = list(range(n_df1 + n_df2 + n_df3 + 1, n_df1 + 
                                n_df2 + n_df3 + n_df4 + 1))
)


df_demo = pd.concat([df1_frame, df2_frame, df3_frame, df4_frame])
df_demo = df_demo.set_axis(["id", "gender","age", "race" , 
                            "education", "marital", 
                            "examination",
                            "pseudo-sup",
                            "pseudo-stra",
                            "mec",
                            "interviewed", "cohort"], axis=1)
df_demo = df_demo.astype({'id': 'int64'})
df_demo = df_demo.astype({'id': 'string'})
df_demo = df_demo.astype({'race': 'string'})
df_demo = df_demo.astype({'education': 'string'})
df_demo = df_demo.astype({'marital': 'string'})
df_demo = df_demo.astype({'examination': 'string'})
df_demo = df_demo.astype({'mec': 'string'})
df_demo = df_demo.astype({'interviewed': 'string'})


print(df_demo.dtypes)
df_demo.to_pickle('df_demo.pickle')
df_demo

b. Repeat part a for the oral health and dentition data (OHXDEN_*.XPT) retaining the following variables: SEQN, OHDDESTS, tooth counts (OHXxxTC), and coronal cavities (OHXxxCTC).

In [ ]:
col = ['SEQN', 'OHDDESTS']
for i in range(1, 10):
    col.append('OHX0'+str(i)+'TC')
    col.append('OHX0'+str(i)+'CTC')
for i in range(10, 32):
    col.append('OHX'+str(i)+'TC')
    col.append('OHX'+str(i)+'CTC')
col.remove("OHX16CTC")
col.remove("OHX17CTC")
col.remove("OHX01CTC")
    
    
    
df1 = pd.read_sas('OHXDEN_G.XPT')
df1 = df1[col]
n_df1 = df1.shape[0]
df1['cohort'] = ['2011-2012'] * n_df1

dic_df1 = {}
for name in df1.columns:
    dic_df1[name] = list(df1[name])
df1_frame = pd.DataFrame(
    dic_df1, index = list(range(1, n_df1+1))
)


df2 = pd.read_sas('OHXDEN_H.XPT')
df2 = df2[col]
n_df2 = df2.shape[0]
df2['cohort'] = ['2013-2014'] * n_df2

dic_df2 = {}
for name in df2.columns:
    dic_df2[name] = list(df2[name])
df2_frame = pd.DataFrame(
    dic_df2, index = list(range(n_df1 + 1, n_df1 + n_df2 + 1))
)

df3 = pd.read_sas('OHXDEN_I.XPT')
df3 = df3[col]
n_df3 = df3.shape[0]
df3['cohort'] = ['2015-2016'] * n_df3

dic_df3 = {}
for name in df3.columns:
    dic_df3[name] = list(df3[name])
df3_frame = pd.DataFrame(
    dic_df3, index = list(range(n_df1 + n_df2 + 1, n_df1 + n_df2 + 
                                n_df3 + 1))
)

df4 = pd.read_sas('OHXDEN_J.XPT')    
df4 = df4[col]
n_df4 = df4.shape[0]
df4['cohort'] = ['2017-2018'] * n_df4

dic_df4 = {}
for name in df4.columns:
    dic_df4[name] = list(df4[name])
df4_frame = pd.DataFrame(
    dic_df4, index = list(range(n_df1 + n_df2 + n_df3 + 1, n_df1 + 
                                n_df2 + n_df3 + n_df4 + 1))
)


df_oral = pd.concat([df1_frame, df2_frame, df3_frame, df4_frame])
df_oral.rename(columns={'SEQN':'id'}, inplace=True)


print(df_oral.dtypes)
df_oral.to_pickle('df_oral.pickle')
df_oral

c. In your notebook, report the number of cases there are in the two datasets above.

In [ ]:
print("The number of cases in the first dataset is " 
      + str(df_demo.shape[0]) + '.')
print("The number of cases in the second dataset is " 
      + str(df_oral.shape[0]) + '.')